version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      APP_ENV: dev
      APP_SECRET: your_secret_key
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
